version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command:
      - --default-authentication-plugin=mysql_native_password
