sudo: required

language: go

go:
  - 1.7.x
  - 1.8.x

services:
  - mysql
  - docker

env:
  global:
    - MYSQL_USER="root"
    - MYSQL_HOST="127.0.0.1"
    - MYSQL_PORT="3406"
    - PCT_TEST_MYSQL_DSN="${MYSQL_USER}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/?parseTime=true"
  matrix:
    - MYSQL_IMAGE=mysql:5.6
    - MYSQL_IMAGE=mysql:5.7
    - MONGODB_IMAGE=mongo:3.2
    - MONGODB_IMAGE=mongo:3.4

addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.percona.com/apt trusty testing'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x8507EFA5'
    packages:
      - percona-toolkit

install:
  - go get -u github.com/Masterminds/glide
  # remove vendor dir and re-fetch it to check later if it's correct with `git diff --exit-code`
  - rm -rf vendor/
  - glide install

before_script:
  # run docker containers
  - docker-compose up -d
  # check if vendor dir is correct
  - git diff --exit-code
  # turn on profiling on mongo instance
  - mongo --eval 'db.setProfilingLevel(2)'
  # wait for MySQL to become available
  - |
    until mysql -u"${MYSQL_USER}" -h "${MYSQL_HOST}" -P "${MYSQL_PORT}" -e 'SELECT 1' > /dev/null; do
      >&2 echo "MySQL ${MYSQL_HOST}:${MYSQL_PORT} for user ${MYSQL_USER} is unavailable - sleeping"
      sleep 1
    done
    >&2 echo "MySQL ${MYSQL_HOST}:${MYSQL_PORT} is up"

script:
  - test/runner.sh

notifications:
  email:
    on_success: change
    on_failure: change
