dist: trusty
sudo: required

language: go

go:
  - 1.9.x
  - 1.10.x

services:
  - docker

env:
  global:
    - MYSQL_USER="root"
    - MYSQL_HOST="127.0.0.1"
    - MYSQL_PORT="3406"
    - PCT_TEST_MYSQL_DSN="${MYSQL_USER}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/?parseTime=true"
    # For pt-mysql-summary to run MySQL client binary from docker.
    # https://github.com/percona/percona-toolkit/blob/b79a6c621b948fadc6b1192a5ecacb394a6b24f6/bin/pt-mysql-summary#L848
    #- CMD_MYSQL="docker-compose exec mysql mysql"
    #- CMD_MYSQLDUMP="docker-compose exec mysql mysqldump"
  matrix:
    - MYSQL_IMAGE=mysql:5.5
    - MYSQL_IMAGE=mysql:5.6
    - MYSQL_IMAGE=mysql:5.7
    - MYSQL_IMAGE=mysql:8.0
    - MYSQL_IMAGE=percona/percona-server:5.6
    - MYSQL_IMAGE=percona/percona-server:5.7
    # percona:5.5 doesn't pass one test, not really sure why as other 5.5 images work.
    #- MYSQL_IMAGE=percona:5.5
    - MYSQL_IMAGE=percona:5.6
    - MYSQL_IMAGE=percona:5.7
    - MYSQL_IMAGE=mariadb:5.5
    - MYSQL_IMAGE=mariadb:10.0
    - MYSQL_IMAGE=mariadb:10.1
    # pt-mysql-summary hangs on mariadb:10.2
    # https://jira.percona.com/browse/PT-1549
    #- MYSQL_IMAGE=mariadb:10.2
    - MONGODB_IMAGE=mongo:3.2
    - MONGODB_IMAGE=mongo:3.4
    - MONGODB_IMAGE=mongo:3.6
    - MONGODB_IMAGE=percona/percona-server-mongodb:3.2
    - MONGODB_IMAGE=percona/percona-server-mongodb:3.4
    - MONGODB_IMAGE=percona/percona-server-mongodb:3.6

addons:
  apt:
    sources:
      - sourceline: "deb http://repo.percona.com/apt $(lsb_release -s -c) main"
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x8507EFA5'
    packages:
      - percona-toolkit

install:
  - go get -u github.com/Masterminds/glide
  # remove vendor dir and re-fetch it to check later if it's correct with `git diff --exit-code`
  - rm -rf vendor/
  - glide install

before_script:
  # check if vendor dir is correct
  - git diff --exit-code
  # run docker containers
  - docker-compose up -d
  # wait for MySQL to become available
  - ./with_backoff.sh docker-compose exec mysql mysql --protocol=tcp -u"${MYSQL_USER}" -e 'SELECT 1'
  # log versions
  - docker --version
  - docker-compose --version
  - docker-compose exec mysql mysql --version
  - docker-compose exec mongo mongo --version
  # we need at least one document in test db
  - mongo --eval 'db.init.insert({})'
  # show logs from all components
  - docker-compose logs

script:
  - test/runner.sh

notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: A/jke9SzibxoGc0H86z5fnGKoLr6xTPBNUcjLMVJ2xzqp8HX90gOdWKenooCu6tyJ0gXX8nUgIOQWsupICy2P2HPGXXKonY4Lq1qRPbxXnlqweaoTf2IZ8SmQeyP6TvNZF9978YRLqRBmJXzq7dcZCF2Gr/1XLPDCNIVJcKgG+heVUubt6q8EnIzB4OYKwUJwZ2ORzleLwqzs8ViB5ffmOXmAVd80rUTcCOailKE4+ML+CQO1MLbGxbdVjacivjM0cvXoibRZF5bhUsg7qoszaWJidJjX9UtW9rRKyPuh1vh1HFgayxmWNeiqe7yyIwGZU37Gnten+4XsVpKYxSOfRWz8TNu01jdDs7e8RgJ29OCwVG88y/yxrBtDlhjsKvy7owV1eAH63YVUJzgoVQZKUt04LAKTMxjEZKBb7o7+GdmSHQWPj8NNmcPEWBwSg99yU3xTQXefgLjqiCQTTNaiNEa1JgPNroKXzAcjJ12qpY5F5MWPFZ2ndTOL2kVEn4iqV7t6bresISXAZKJn+IrjUdZ+ZBr48zcnO7rgWGvszScDWt3oqjRlCbwxXWTL8VoDouylGVAJTUHxo07Bs307cwYiLsUp/2hPvcY2ELXrQXTqk3ZHJkMHa4U+nNvXY9RYNNqFmvAnUCHG6JfBda4b0SCjbCINjQVMCsF5DSXua8=
