version: '3'
services:
  mysql:
    image: ${MYSQL_IMAGE:-mysql:5.7}
    ports:
      - ${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command:
      # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
      # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
      - --performance-schema
      - --secure-file-priv=""
      # github.com/go-sql-driver/mysql doesn't support new default auth plugin in MySQL 8
      # https://github.com/go-sql-driver/mysql/issues/785
      # https://github.com/go-sql-driver/mysql/pull/552
      - --default-auth=mysql_native_password
    volumes:
      - ./test/schema/:/docker-entrypoint-initdb.d/:rw
  mongo:
    image: ${MONGODB_IMAGE:-mongo:3.6}
    ports:
      - ${MONGODB_HOST:-127.0.0.1}:${MONGODB_PORT:-27017}:27017
    # MongoDB doesn't enable profiling by default
    command: --profile 2
