version: '3'
services:
  mysql:
    image: ${MYSQL_IMAGE:-mysql:5.7}
    ports:
      - ${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  mongo:
    image: ${MONGODB_IMAGE:-mongo:3.4}
    ports:
      - ${MONGODB_HOST:-127.0.0.1}:${MONGODB_PORT:-27017}:27017
