[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
# Removing unused sub-packages sounds like a great idea until you need one.
#  unused-packages = true
