[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  revision = "cee8f7dd22c76b109ebf3bb52fe74e74fa65175b"

[prune]
  non-go = true
  go-tests = true
# Removing unused sub-packages sounds like a great idea until you need one.
#  unused-packages = true
